global:
  resolve_timeout: 5m

route:
  receiver: Alertmanager
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'Alertmanager'
    slack_configs:
      - api_url: 'DISCORD_WEBHOOK_HERE'
        username: 'Alertmanager'
        send_resolved: true
        text: "Alert: {{ .CommonLabels.alertname }}"

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
