global:
  resolve_timeout: 5m

route:
  receiver: Alertmanager
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'Alertmanager'
    slack_configs:
      - api_url: 'DISCORD_WEBHOOK_HERE'
        channel: '#your_channel'
        username: 'Alertmanager'
        send_resolved: true
        title: |-
          [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}
        text: |-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.title }}  
          *Description:* {{ .Annotations.description }}  
          *Details:* {{ range .Labels.SortedPairs }} `{{ .Name }}: {{ .Value }}` {{ end }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
