global:
  resolve_timeout: 5m

route:
  receiver: discord-webhook
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'Alertmanager'
    webhook_configs:
      - url: 'DISCORD_WEBHOOK_HERE'
        send_resolved: true
        max_alerts: 1  # Adjust to avoid rate limiting by Discord
        http_config:
          follow_redirects: true  # Ensures redirects are followed if needed

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
