global:
  resolve_timeout: 5m

route:
  # Define the default route for alerts
  receiver: discord-webhook
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'discord-webhook'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1285592497229402194/ZF_2iy9wmEOkIamM5XxoQy376m-yFfPogyMIFXfVZd7OGJbkCLjmzBrq8w9OeeJLPsr0'
        send_resolved: true
        http_config:
          follow_redirects: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
