global:
  resolve_timeout: 5m

route:
  receiver: discord
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: discord
    discord_configs:
      - webhook_url: 'DISCORD_WEBHOOK'
        title: 'Alert: {{ .GroupLabels.alertname }}'
        message: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.title }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
