global:
  resolve_timeout: 5m

route:
  receiver: discord
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: discord
    discord_configs:
      - webhook_url: 'DISCORD_WEBHOOK'
        message: '{{ template "custom.discord.message" . }}'
        title: '{{ template "custom.discord.title" . }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
