# Global configuration
global:
  scrape_interval: 1m           # Set the scrape interval to every 1 minute.
  evaluation_interval: 1m       # Evaluate rules every 1 minute.
  # Attach external labels to any time series or alerts when communicating with external systems.
  external_labels:
    monitor: "monitoring-vmangos-docker"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # Define rule files here if needed.
  # - "first.rules"
  # - "second.rules"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus metrics
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]  # Scrape Prometheus itself on port 9090

  # Scrape Docker daemon metrics
  - job_name: docker
    static_configs:
      - targets: ["localhost:9323"]  # Scrape Docker metrics exposed on localhost:9323
