global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'  # Connect Prometheus to Alertmanager

# Load alert rules from the specified file
rule_files:
  - "/etc/prometheus/alert.rules.yml"  # Path to your alert rules file

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']  # Optional: Monitor Alertmanager itself

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Optional: Monitor Grafana if necessary
